"""
    expert.ai Extract

    Expert.ai Extract provides layout recognition for PDF documents by detecting and extracting:  - Text with reading order - Titles and headings - Headers and footers - Tables - Document metadata - Pages count  The textual elements are returned together with the number of the page in which they occur and their bounding box.   # noqa: E501

    The version of the OpenAPI document: v1
    Contact: api.inquiry@expert.ai
    Generated by: https://openapi-generator.tech
"""

import unittest


class TestRecognitionTaskOutput(unittest.TestCase):
    """RecognitionTaskOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecognitionTaskOutput(self):
        """Test RecognitionTaskOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecognitionTaskOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
