"""
    expert.ai Estratto

    Expert.ai Estratto provides layout recognition for PDF documents by detecting and extracting:  - Text with reading order - Titles and headings - Headers and footers - Tables - Document metadata - Pages count  The textual elements are returned together with the number of the page in which they occur and their bounding box.   # noqa: E501

    The version of the OpenAPI document: v1
    Contact: api.inquiry@expert.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

from expertai.extract.openapi.client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_layout_document_async_post(self):
        """Test case for layout_document_async_post

        """
        pass

    def test_status_task_id_get(self):
        """Test case for status_task_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
